FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod tidy

COPY . .

RUN go build -o temperature-api .

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/temperature-api .

EXPOSE 8081

ENV PORT=8081

CMD ["./temperature-api"]

